-- MySQL Script generated by MySQL Workbench
-- Thu May 30 15:00:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_Agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sistema_Agenda` ;

-- -----------------------------------------------------
-- Schema Sistema_Agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema_Agenda` DEFAULT CHARACTER SET utf8 ;
USE `Sistema_Agenda` ;

-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(9) NULL,
  `correo_electronico` VARCHAR(255) NOT NULL,
  `direccion_exacta` VARCHAR(350) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE,
  UNIQUE INDEX `direccion_exacta_UNIQUE` (`direccion_exacta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(9) NOT NULL,
  `correo_electronico` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(300) NULL,
  `fecha_nacimiento` DATE NULL,
  `contrasenna` VARCHAR(24) NOT NULL,
  `rol` ENUM('Cliente', 'Encargado', 'Administrador') NOT NULL,
  `estado` TINYINT NULL,
  `idSucursal` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `direccion_UNIQUE` (`direccion` ASC) VISIBLE,
  UNIQUE INDEX `fecha_nacimiento_UNIQUE` (`fecha_nacimiento` ASC) VISIBLE,
  UNIQUE INDEX `contrasenna_UNIQUE` (`contrasenna` ASC) VISIBLE,
  UNIQUE INDEX `rol_UNIQUE` (`rol` ASC) VISIBLE,
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC) VISIBLE,
  INDEX `FK_Sucursal_Usuario_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `FK_Sucursal_Usuario`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Sistema_Agenda`.`Sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `precio` FLOAT NULL,
  `estado` TINYINT NULL,
  `idCategoria` INT NOT NULL,
  `idMarca` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Categoria_Producto_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `FK_Marca_Producto_idx` (`idMarca` ASC) VISIBLE,
  CONSTRAINT `FK_Categoria_Producto`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Sistema_Agenda`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Marca_Producto`
    FOREIGN KEY (`idMarca`)
    REFERENCES `Sistema_Agenda`.`Marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Estado` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Especialidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `nivel_atencio` VARCHAR(255) NOT NULL,
  `idEspecialidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Especialidad_Servicio_idx` (`idEspecialidad` ASC) VISIBLE,
  CONSTRAINT `FK_Especialidad_Servicio`
    FOREIGN KEY (`idEspecialidad`)
    REFERENCES `Sistema_Agenda`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `foto` VARCHAR(255) NULL,
  `idEspecilidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Especialidad_Medico_idx` (`idEspecilidad` ASC) VISIBLE,
  CONSTRAINT `FK_Especialidad_Medico`
    FOREIGN KEY (`idEspecilidad`)
    REFERENCES `Sistema_Agenda`.`Especialidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `idEstado` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `idCliente`),
  INDEX `FK_UsuarioCliente_Reserva_idx` (`idCliente` ASC) VISIBLE,
  INDEX `FK_Estado_Reserva_idx` (`idEstado` ASC) VISIBLE,
  INDEX `FK_Servicio_Reserva_idx` (`idServicio` ASC) VISIBLE,
  INDEX `FK_Medico_Reserva_idx` (`idMedico` ASC) VISIBLE,
  INDEX `FK_Sucursal_Cita_idx` (`idSucursal` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Cita`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Sistema_Agenda`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Estado_Cita`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Sistema_Agenda`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Servicio_Cita`
    FOREIGN KEY (`idServicio`)
    REFERENCES `Sistema_Agenda`.`Servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Medico_Cita`
    FOREIGN KEY (`idMedico`)
    REFERENCES `Sistema_Agenda`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sucursal_Cita`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Sistema_Agenda`.`Sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Dia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Horario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `Horariocol` TIME NOT NULL,
  `idSucursal` INT NOT NULL,
  `estado` TINYINT NULL,
  `idDia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Sucursal_Horario_idx` (`idSucursal` ASC) VISIBLE,
  INDEX `FK_Dia_Horario_idx` (`idDia` ASC) VISIBLE,
  CONSTRAINT `FK_Sucursal_Horario`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `Sistema_Agenda`.`Sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Dia_Horario`
    FOREIGN KEY (`idDia`)
    REFERENCES `Sistema_Agenda`.`Dia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` DECIMAL NULL,
  `estado` TINYINT NULL,
  `idUsuario` INT NOT NULL,
  `idScursal` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Usuario_Factura_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `FK_Sucursal_Factura_idx` (`idScursal` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Factura`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Sistema_Agenda`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sucursal_Factura`
    FOREIGN KEY (`idScursal`)
    REFERENCES `Sistema_Agenda`.`Sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Factura_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Factura_Detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFactura` INT NOT NULL,
  `subtotal` DECIMAL NOT NULL,
  `estado` TINYINT NULL,
  `idProducto` INT NULL,
  `idCita` INT NOT NULL,
  PRIMARY KEY (`id`, `idFactura`),
  INDEX `FK_Factura_Factura_Detalle_idx` (`idFactura` ASC) VISIBLE,
  INDEX `FK_Producto_Factura_Detalle_idx` (`idProducto` ASC) VISIBLE,
  INDEX `FK_Cita_Factura_Detalle_idx` (`idCita` ASC) VISIBLE,
  CONSTRAINT `FK_Factura_Factura_Detalle`
    FOREIGN KEY (`idFactura`)
    REFERENCES `Sistema_Agenda`.`Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Producto_Factura_Detalle`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Sistema_Agenda`.`Producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cita_Factura_Detalle`
    FOREIGN KEY (`idCita`)
    REFERENCES `Sistema_Agenda`.`Cita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Agenda`.`Subservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Agenda`.`Subservicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tiempo` INT NOT NULL,
  `descripción` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Servicio_Subservicio_idx` (`idServicio` ASC) VISIBLE,
  CONSTRAINT `FK_Servicio_Subservicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `Sistema_Agenda`.`Servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
